#ifndef LUNASVG_EXPORT_H
#define LUNASVG_EXPORT_H

#ifdef LUNASVG_STATIC_DEFINE
#  define LUNASVG_EXPORT
#  define LUNASVG_NO_EXPORT
#else
#  ifndef LUNASVG_EXPORT
#    define LUNASVG_EXPORT @LUNASVG_EXPORT@
#  endif
#  ifndef LUNASVG_NO_EXPORT
#    define LUNASVG_NO_EXPORT @LUNASVG_NO_EXPORT@
#  endif
#endif

#ifndef LUNASVG_DEPRECATED
#  define LUNASVG_DEPRECATED @LUNASVG_DEPRECATED@
#endif

#ifndef LUNASVG_DEPRECATED_EXPORT
#  define LUNASVG_DEPRECATED_EXPORT LUNASVG_EXPORT LUNASVG_DEPRECATED
#endif

#ifndef LUNASVG_DEPRECATED_NO_EXPORT
#  define LUNASVG_DEPRECATED_NO_EXPORT LUNASVG_NO_EXPORT LUNASVG_DEPRECATED
#endif

#endif /* LUNASVG_EXPORT_H */
